name: flutter_fb_news
description: Flutter plugin for displaying Facebook page feed with photos and videos
version: 1.1.4-dev.3
homepage: https://github.com/cedteg/flutter_fb_news
repository: https://github.com/cedteg/flutter_fb_news
issue_tracker: https://github.com/cedteg/flutter_fb_news/issues

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.0
  chewie: ^0.12.2
  flutter_linkify: ^4.0.2
  http: ^0.12.2
  url_launcher: ^5.7.10
  video_player: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
